name: debug log
on: push
defaults:
  run:
   shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  before:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: generate
        run: echo "result=Hello" >> ${GITHUB_OUTPUT}    
    outputs:
      result: ${{ steps.generate.outputs.result }}
  
  after:
    runs-on: ubuntu-latest
    needs: [before]
    steps:
      - env:
          RESULT: ${{ needs.before.outputs.result }}
        run: echo "${RESULT}"