name: debug log
on: push
defaults:
  run:
   shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  log:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          set -x
          echo "::group::環境変数表示"
          date
          echo "::debug::デバッグログです"
          printenv
          echo "::endgroup::"
      - run: echo "::add-mask::${PASSWORD}"
        env:
            PASSWORD: superSecret
      - run: echo "::notice::情報ログです" 